import { useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowUpRight, Check, Smartphone, QrCode } from 'lucide-react'
import { catalog, price } from './store'
import './label-journey.css'
const server = import.meta.env.VITE_SERVER_MODE === 'true'
export function LabelJourney({base='/shop',compact=false}:{base?:string;compact?:boolean}) {
 const [need,setNeed]=useState('Everyday')
 const options=[['Everyday','Bottles & books'],['Clothing','Clothes'],['Tech','Cables & chargers'],['Bags & keys','Bags & keys'],['NFC','Tap to find'],['Bundles','Label kit'],['Finders','Premium finder']]
 const picks=catalog.filter(p=>p.category===need)
 return <section className={'fl-journey'+(compact?' fl-compact':'')} aria-label="Choose your labelling option" id="labels">
 <div className="fl-heading"><div><p className="fb-kicker">START WITH WHAT YOU LOVE</p><h2>A label for your life.<br/><em>A way back for your things.</em></h2></div><p>Buy your labels. Connect them in FindBox.<br/>Keep every belonging in one place.</p></div>
 <div className="fl-options" role="group" aria-label="What are you labelling?">{options.map(([value,label])=><button key={value} aria-pressed={need===value} onClick={()=>setNeed(value)}>{label}</button>)}</div>
 <div className="fl-picks">{picks.map(p=><article key={p.id}><Link to={base+'/products/'+(server?p.serverId:p.id)}><img src={p.image} alt={p.name+' product mockup'} loading="lazy"/></Link><div><span>{p.format} · {p.count} labels</span><h3>{p.name}</h3><p>{p.description}</p><Link className="fl-button" to={base+'/products/'+(server?p.serverId:p.id)}>{p.available?'Choose this pack':'Explore the finder'} · {price(p.price)} <ArrowUpRight size={17}/></Link>{p.id==='complete'&&<small>Save KSh 445 against buying these packs separately.</small>}</div></article>)}</div>
 {!compact&&<><div className="fl-compare"><div><p className="fb-kicker">TWO WAYS TO CONNECT</p><h2>Scan is simple.<br/><em>Tap is effortless.</em></h2><p>Both lead to the same recovery page. Choose the interaction that suits your everyday.</p></div><article><QrCode/><h3>QR · the everyday essential</h3><p>Open the camera and scan. An affordable choice for labelling more belongings.</p><strong>12 stickers / KSh 499</strong></article><article className="fl-premium"><Smartphone/><span className="fl-badge">PREMIUM CONVENIENCE</span><h3>NFC + QR · the easy upgrade</h3><p>Hold a compatible phone close to open the recovery page. No camera framing, no battery. QR is included as a fallback.</p><strong>3 tags / KSh 999</strong><Link to={base+'/products/'+(server?'tap-3':'tap')}>Explore tap & find <ArrowUpRight size={16}/></Link></article></div><p className="fl-footnote">NFC needs a compatible phone and suitable placement; metal can affect reading. Both options need an internet connection to open the recovery page. Neither provides live GPS tracking.</p>
 <div className="fl-flow">{[['01','Choose your labels','Match the material and application to your belongings.'],['02','Join & order','One FindBox account keeps your purchase and tags together.'],['03','Connect in the app','Use the supplied activation code, name the item and choose its owner. No photo required.'],['04','Give it a way home','Attach the label. A scan or tap helps route a found item to the school return process.']].map(([n,title,body])=><div key={n}><span>{n}</span><h3>{title}</h3><p>{body}</p></div>)}</div>
 <div className="fl-join"><div><Check/><h3>Your labels are only the beginning.</h3><p>Your belongings, tag orders and collection updates share one account.</p></div><Link to="/app/sign-up" state={{from:base+'/catalog'}} className="fl-button">Join FindBox <ArrowUpRight size={17}/></Link></div></>}
 </section>
}
export function LabelDetails({id}:{id:string}) {
 const p=catalog.find(p=>p.id===id||p.serverId===id)
 if(!p)return null
 if(p.id==='finder')return <div className="fl-detail"><h3>Premium finder · coming soon</h3><p>An AirTag-style finder uses Bluetooth and a compatible finding network, rather than built-in GPS. The final hardware and supported phones are still being selected.</p><p>Locating and pairing will happen in the supported companion app. FindBox does not currently receive live tracker locations.</p><Link to="/contact">Ask about the Findable Key Card</Link><small>Concept image and target price. Not available to order yet. Not included in the complete label kit.</small></div>
 return <div className="fl-detail"><h3>{p.id==='complete'?'Every type. One kit.':'The right finish for the job.'}</h3><p>{p.id==='complete'?'12 everyday + 12 fabric + 6 cable + 6 charger labels + 2 engraved tags + 3 NFC tags. 41 labels; save KSh 445.':p.uses.join(' · ')}</p><p>After collection, open <Link to="/app/shop/account#tags">My tags in the app</Link> to connect each supplied label to a belonging. Your personal details are not printed on the label.</p><small>Proposed launch price. Application and material specifications will be confirmed before live sales. Product mockups show suggested use; belongings are not included.</small></div>
}
