import { create } from 'zustand'
import { persist } from 'zustand/middleware'
export const catalog=[
{id:'everyday',name:'Everyday labels',subtitle:'For all the little essentials.',price:499,count:12,format:'QR stickers',category:'Everyday',image:'/media/catalog/bottle-960.webp',description:'A simple way back for water bottles, lunch boxes, books and stationery. Twelve individual tag identities, ready to connect to the things you use every day.',uses:['Bottles & lunch boxes','Books & stationery','Hard, smooth surfaces'],color:'#d6e9ef'},
{id:'uniform',name:'Uniform essentials',subtitle:'For the jumper that looks like theirs.',price:599,count:12,format:'Fabric QR labels',category:'Clothing',image:'/media/catalog/clothing-960.webp',description:'Make school uniforms recognisably yours. Give each sweater, PE kit and jacket its own identity, with a private route back through your school.',uses:['School uniforms','PE & sports clothing','Sweaters & jackets'],color:'#f0ddc9'},
{id:'adventure',name:'Adventure tags',subtitle:'For wherever the day takes you.',price:399,count:2,format:'Loop QR tags',category:'Bags & keys',image:'/media/objects/airtag-1280.webp',description:'A pair of easy-to-attach identification tags for bags, keys and sports kits. Scan to reach the school collection instructions. These are identification tags, not GPS trackers.',uses:['School bags','Keys & sports kits','Removable attachment'],color:'#dce4d2'},
{id:'tap',name:'Tap & find',subtitle:'A little tap. A clear way home.',price:699,count:3,format:'NFC + QR',category:'NFC',image:'/media/objects/nfc-1280.webp',description:'Open a belonging’s recovery page with a compatible NFC phone, or scan the QR fallback. Each supplied tag connects to one item in your FindBox app.',uses:['Compatible NFC phones','QR camera fallback','No battery required'],color:'#e4e2ed'}
]
export type Product=typeof catalog[number]
export type StoreOrder={id:string;personId:string;date:string;lines:{productId:string;quantity:number}[];total:number;method:string;status:'confirmed'|'preparing'|'ready'|'collected';school:string}
export type SuppliedTag={code:string;orderId:string;personId:string;productId:string;itemId?:string}
type CommerceState={cart:Record<string,number>;orders:StoreOrder[];tags:SuppliedTag[];change:(id:string,quantity:number)=>void;place:(personId:string,method:string,school:string)=>string;activate:(code:string,itemId:string)=>void;advance:(id:string,personId:string)=>void}
export const useCommerce=create<CommerceState>()(persist((set,get)=>({cart:{},orders:[],tags:[],change:(id,quantity)=>{if(!catalog.some(p=>p.id===id))return;set(s=>({cart:{...s.cart,[id]:Math.max(0,Math.min(10,quantity))}}))},place:(personId,method,school)=>{const lines=Object.entries(get().cart).filter(([,q])=>q>0&&q<=10).map(([productId,quantity])=>({productId,quantity}));if(!lines.length)throw new Error('Your bag is empty');const orderId='FB-'+crypto.randomUUID().slice(0,8).toUpperCase();const total=lines.reduce((sum,l)=>sum+(catalog.find(p=>p.id===l.productId)?.price||0)*l.quantity,0);const tags=lines.flatMap(l=>Array.from({length:catalog.find(p=>p.id===l.productId)!.count*l.quantity},()=>({code:'FB-P-'+crypto.randomUUID().slice(0,8).toUpperCase(),orderId,personId,productId:l.productId})));set(s=>({orders:[{id:orderId,personId,date:new Date().toISOString(),lines,total,method,status:'confirmed',school},...s.orders],tags:[...tags,...s.tags],cart:{}}));return orderId},activate:(code,itemId)=>set(s=>({tags:s.tags.map(t=>t.code===code?{...t,itemId}:t)})),advance:(id,personId)=>set(s=>({orders:s.orders.map(o=>o.id===id&&o.personId===personId?{...o,status:o.status==='confirmed'?'preparing':o.status==='preparing'?'ready':'collected'}:o)}))}),{name:'findbox.store.preview.v1'}))
export const price=(value:number)=>'KSh '+value.toLocaleString('en-KE')
