import { create } from 'zustand'
import { persist } from 'zustand/middleware'
import products from './catalog.json'
export const catalog=products
export type Product=typeof catalog[number]
export type StoreOrder={id:string;personId:string;date:string;lines:{productId:string;quantity:number;unitPrice?:number}[];total:number;method:string;status:'confirmed'|'preparing'|'ready'|'collected';school:string}
export type SuppliedTag={code:string;orderId:string;personId:string;productId:string;itemId?:string;format?:string}
type CommerceState={cart:Record<string,number>;orders:StoreOrder[];tags:SuppliedTag[];change:(id:string,quantity:number)=>void;place:(personId:string,method:string,school:string)=>string;activate:(code:string,itemId:string)=>void;advance:(id:string,personId:string)=>void}
export const useCommerce=create<CommerceState>()(persist((set,get)=>({cart:{},orders:[],tags:[],change:(id,quantity)=>{if(!catalog.some(p=>p.id===id))return;set(s=>({cart:{...s.cart,[id]:Math.max(0,Math.min(10,quantity))}}))},place:(personId,method,school)=>{const lines=Object.entries(get().cart).filter(([id,q])=>q>0&&q<=10&&catalog.some(p=>p.id===id)).map(([productId,quantity])=>({productId,quantity,unitPrice:catalog.find(p=>p.id===productId)!.price}));if(!lines.length)throw new Error('Your bag is empty');const orderId='FB-'+crypto.randomUUID().slice(0,8).toUpperCase();const total=lines.reduce((sum,l)=>sum+(catalog.find(p=>p.id===l.productId)?.price||0)*l.quantity,0);const tags=lines.flatMap(l=>Array.from({length:catalog.find(p=>p.id===l.productId)!.count*l.quantity},(_,i)=>({format:l.productId==='complete'?([...Array(12).fill('sticker'),...Array(12).fill('fabric'),...Array(6).fill('wrap'),...Array(6).fill('compact'),...Array(2).fill('engraved'),...Array(3).fill('nfc')][i%41]):catalog.find(p=>p.id===l.productId)!.stockFormat,code:'FB-P-'+crypto.randomUUID().slice(0,8).toUpperCase(),orderId,personId,productId:l.productId})));set(s=>({orders:[{id:orderId,personId,date:new Date().toISOString(),lines,total,method,status:'confirmed',school},...s.orders],tags:[...tags,...s.tags],cart:{}}));return orderId},activate:(code,itemId)=>set(s=>({tags:s.tags.map(t=>t.code===code?{...t,itemId}:t)})),advance:(id,personId)=>set(s=>({orders:s.orders.map(o=>o.id===id&&o.personId===personId?{...o,status:o.status==='confirmed'?'preparing':o.status==='preparing'?'ready':'collected'}:o)}))}),{name:'findbox.store.preview.v1'}))
export const price=(value:number)=>'KSh '+value.toLocaleString('en-KE')
