import { chromium } from 'playwright';
import { mkdir } from 'node:fs/promises';
const base=process.env.BASE||'http://localhost:5173';await mkdir('shots/commerce',{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const failures=[];page.on('pageerror',e=>failures.push(e.message));page.on('request',r=>{if(new URL(r.url()).pathname.startsWith('/api/'))failures.push('Frontend contacted backend: '+r.url())});
await page.goto(base+'/');await page.getByRole('link',{name:'Find your tags',exact:true}).click();await page.getByRole('heading',{name:'Little labels. Big peace of mind.'}).waitFor();await page.screenshot({path:'shots/commerce/store-desktop.png',fullPage:true});
await page.goto(base+'/shop/products/everyday');await page.getByRole('button',{name:/Add to bag/}).click();await page.getByRole('link',{name:/View bag/}).click();await page.getByRole('link',{name:/Continue to checkout/}).click();await page.getByRole('button',{name:/Sign in to continue/}).click();await page.getByRole('button',{name:/Amina Wekesa/}).click();await page.getByRole('heading',{name:'Make it yours.',exact:true}).waitFor();await page.screenshot({path:'shots/commerce/checkout-desktop.png',fullPage:true});await page.getByRole('radio',{name:/M-Pesa/}).check();await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Place sample order'}).click();await page.getByRole('heading',{name:'You’re all set.'}).waitFor();await page.getByRole('button',{name:/Preview next order stage/}).click();await page.getByRole('button',{name:/Preview next order stage/}).click();await page.getByRole('heading',{name:'Ready when you are.'}).waitFor();await page.getByRole('link',{name:/Explore your tags/}).click();await page.getByRole('button',{name:/Connect a belonging/}).first().click();await page.getByLabel('Belonging name').fill('My connected preview bottle');await page.getByLabel('Belongs to').selectOption('s-zuri');await page.getByRole('button',{name:/Connect to the app/}).click();await page.getByRole('link',{name:/View belonging/}).first().click();await page.getByRole('heading',{name:'My connected preview bottle',exact:true}).waitFor();
await page.goto(base+'/app/home');await page.waitForTimeout(700);await page.screenshot({path:'shots/commerce/original-app-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});for(const [name,url] of [['store','/shop'],['catalog','/shop/catalog'],['product','/shop/products/uniform'],['account','/shop/account'],['app','/app/home'],['help','/shop/help']]){await page.goto(base+url);await page.waitForTimeout(500);await page.screenshot({path:'shots/commerce/'+name+'-mobile.png',fullPage:true});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))failures.push('Overflow: '+url)}
await browser.close();if(failures.length)throw new Error(failures.join('\n'));console.log('Commerce checks passed: main landing → store → product → bag → login → checkout → order tracking → activate tag → original app; mobile layouts; no API requests.');
