import { chromium } from 'playwright'
import { mkdirSync } from 'node:fs'
import assert from 'node:assert/strict'
mkdirSync('shots/experience', { recursive: true })
const browser = await chromium.launch({ channel: 'chrome' })
const errors = []
for (const width of [1440, 390]) {
  const page = await browser.newPage({ viewport: { width, height: 950 }, serviceWorkers: 'block' })
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('http://127.0.0.1:4175/')
  await page.waitForTimeout(2500)
  await page.getByRole('button', { name: 'NFC tag' }).click()
  assert.equal(await page.getByRole('button', { name: 'NFC tag' }).getAttribute('aria-pressed'), 'true')
  await page.getByRole('button', { name: 'Pause object motion' }).click()
  await page.screenshot({ path: `shots/experience/hero-${width}.png`, fullPage: true })
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
  await page.goto('http://127.0.0.1:4175/demo')
  await page.getByRole('button', { name: /^Student/ }).first().click()
  await page.goto('http://127.0.0.1:4175/app/quest')
  await page.getByRole('button', { name: 'Coastal scout', exact: true }).click()
  await page.reload()
  assert.equal(await page.getByRole('button', { name: 'Coastal scout', exact: true }).getAttribute('aria-pressed'), 'true')
  const before = await page.evaluate(() => JSON.parse(localStorage.getItem('findbox.v1')).state.ledger)
  await page.getByRole('button', { name: /Scan its tag and hand it to staff/ }).click()
  await page.getByRole('button', { name: /Next challenge/ }).click()
  await page.getByRole('button', { name: /Refresh the label in FindBox/ }).click()
  await page.getByRole('button', { name: /Next challenge/ }).click()
  await page.getByRole('button', { name: /School staff, after checking ownership/ }).click()
  await page.getByRole('button', { name: /Finish training/ }).click()
  assert.ok(await page.getByRole('heading', { name: /3\/3/ }).isVisible())
  assert.deepEqual(await page.evaluate(() => JSON.parse(localStorage.getItem('findbox.v1')).state.ledger), before)
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: `shots/experience/quest-${width}.png`, fullPage: true })
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
  await page.close()
}
await browser.close()
assert.deepEqual(errors, [])
console.log('Passed: desktop/mobile selection, motion toggle, avatar persistence, training, unchanged ledger, layout and runtime checks.')
