import { chromium } from 'playwright'
import assert from 'node:assert/strict'
import { mkdirSync, writeFileSync } from 'node:fs'
const origin = process.env.TEST_ORIGIN || 'http://127.0.0.1:4177'
mkdirSync('shots/pwa', { recursive: true })
const browser = await chromium.launch({ channel: 'chrome' })
const context = await browser.newContext({ viewport: { width: 393, height: 852 }, deviceScaleFactor: 3, isMobile: true, hasTouch: true, reducedMotion: 'reduce', serviceWorkers: 'allow' })
const page = await context.newPage()
const errors = []; const requests = []
page.on('pageerror', e => errors.push(e.message))
page.on('request', r => requests.push(r.url()))
await page.goto(origin + '/app')
await page.getByRole('heading', { name: 'Your world, connected.' }).waitFor()
await page.getByRole('navigation', { name: 'Account access' }).getByRole('link', { name: 'Sign up' }).waitFor()
await page.evaluate(() => navigator.serviceWorker.ready.then(() => true))
await page.reload()
await page.waitForFunction(() => !!navigator.serviceWorker.controller)
const manifest = await (await context.request.get(origin + '/manifest.webmanifest')).json()
assert.equal(manifest.start_url, '/app/sign-in?source=homescreen')
for (const icon of manifest.icons) assert.equal((await context.request.get(origin + icon.src)).status(), 200)
const initialScripts = requests.filter(u => u.includes('/assets/') && u.endsWith('.js'))
assert.equal(initialScripts.some(u => /three-engine|scene-|Landing-|charts-/.test(u)), false, 'App login must not load the 3D engine or marketing site')
await page.screenshot({ path: 'shots/pwa/sign-in.png', fullPage: true })
await context.setOffline(true)
await page.goto(origin + '/app')
await page.getByRole('heading', { name: 'Your world, connected.' }).waitFor()
await page.getByRole('button', { name: /Zuri/ }).click()
await page.waitForURL('**/app/home')
await page.getByRole('navigation', { name: 'Mobile primary' }).getByRole('link', { name: 'Inventory', exact: true }).click()
await page.getByRole('heading', { name: 'My inventory' }).waitFor()
await page.locator('.fb-catalog-photo').evaluateAll(imgs => Promise.all(imgs.map(i => { i.loading = 'eager'; return i.decode() })))
assert.equal(await page.locator('.fb-catalog-photo').count(), 4)
await page.screenshot({ path: 'shots/pwa/inventory-offline.png', fullPage: true })
await page.reload()
await page.getByRole('heading', { name: 'My inventory' }).waitFor()
assert.equal(await page.getByRole('navigation', { name: 'Mobile primary' }).getByRole('link', { name: 'Inventory', exact: true }).getAttribute('aria-current'), 'page')
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
// Create a new account offline, then verify its password after signing out.
await page.goto(origin + '/app/sign-up')
await page.getByRole('button', { name: /^Student/ }).click()
await page.getByRole('button', { name: 'Continue', exact: true }).click()
await page.getByLabel('Display name').fill('Mobile Tester')
await page.locator('input[type="email"]').fill('mobile@example.org')
await page.locator('input[type="password"]').fill('Findbox-mobile-2026')
await page.getByRole('button', { name: 'Continue', exact: true }).click()
await page.getByLabel('I am authorised to set up this account').check()
await page.getByRole('button', { name: 'Create account', exact: true }).click()
await page.getByRole('heading', { name: 'Account created' }).waitFor()
await page.getByRole('button', { name: 'Continue', exact: true }).click()
await page.getByRole('button', { name: 'Skip', exact: true }).click()
await page.goto(origin + '/app/account')
await page.getByRole('button', { name: 'Sign out', exact: true }).click()
await page.goto(origin + '/app/sign-in')
await page.locator('input[type="email"]').fill('mobile@example.org')
await page.locator('input[type="password"]').fill('wrong-password')
await page.getByRole('button', { name: 'Sign in', exact: true }).click()
await page.getByRole('alert').filter({ hasText: 'does not match' }).waitFor()
await page.locator('input[type="password"]').fill('Findbox-mobile-2026')
await page.getByRole('button', { name: 'Sign in', exact: true }).click()
await page.waitForURL(/\/app\/(home|account)$/)
await page.reload()
await page.getByRole('link', { name: /Account, Mobile Tester/ }).waitFor()
assert.equal(await page.evaluate(() => Object.values(localStorage).some(v => v.includes('Findbox-mobile-2026'))), false)
for (const [role, name, route] of [['Parent', 'Amina', '/app/home'], ['Teacher', 'Daniel', '/manage']]) {
  await page.goto(origin + '/app/sign-in')
  await page.getByRole('button', { name: role, exact: true }).click()
  await page.getByRole('button', { name: new RegExp(name) }).click()
  await page.waitForURL('**' + route)
  await page.locator('img').evaluateAll(imgs => Promise.all(imgs.map(i => { i.loading = 'eager'; return i.decode() })))
}
await context.setOffline(false)
// Old iOS home-screen bookmarks that start at / must also open sign-in.
await page.addInitScript(() => Object.defineProperty(navigator, 'standalone', { value: true }))
await page.goto(origin)
await page.waitForURL('**/app/sign-in')
assert.deepEqual(errors, [])
const result = { offlineLaunch: true, offlineInventoryAndRefresh: true, offlineSignupAndPasswordSignin: true, wrongPasswordRejected: true, oldHomescreenEntry: true, errors, initialScripts: [...new Set(initialScripts)] }
writeFileSync('shots/pwa/checks.json', JSON.stringify(result, null, 2))
console.log(result)
await browser.close()
